#!/usr/bin/env bash

set -euo pipefail

# Script to download/sync ASIST data.
# Note: gsutil does not work with Python 3.8 on macOS (as of 2020-10-01), but
# it does work with Python 3.7.

mkdir -p $DATA_DIR
gsutil -m rsync -r \
    -x ".*\.mkv|.*\.flv$|.*\.sav$|.*\.m4a$|.*\.mp4$|.*\.vtt$|.*\.tsv$|.*\.gstmp$|.*.png$|.*.PNG$|.*\.csv$|.*Competency.*|.*Condition.*$|Materials/.*$|TrialMessages.*$|Analyses/.*$|.*Posttrial.*$|.*Pretrial.*$|.*EyeTracking.*$" \
    gs://studies.aptima.com/$GCS_DIR $DATA_DIR
