version: '3'

networks:
  asist_net:
   external: true    
    
services:
  uaz_tmm_agent:
    image: uaz_tmm_agent:latest
    container_name: uaz_tmm_agent
    networks:
      asist_net:
        aliases:
          - uaz_tmm_agent
    entrypoint: ["bash", "entrypoint.sh"]
    volumes:
      - ./data/asist/study3_intervention1:/tomcat-tmm/data/asist/study3_intervention1/logs
