#pragma once

#include <memory>
#include <string>

#include "utils/Definitions.h"
#include "pgm/DynamicBayesNet.h"
#include "pipeline/training/DBNTrainer.h"

namespace tomcat {
    namespace model {

        /**
         * Class responsible to save a model's parameters to files in a specific
         * folder.
         */
        class DBNSaver {
          public:
            //------------------------------------------------------------------
            // Constructors & Destructor
            //------------------------------------------------------------------

            /**
             * Creates an instance of the saver.
             *
             * @param model: DBN
             * @param trainer: object that handles parameter learning
             * @param output_folder_path: folder where the model's parameters
             * must be saved in
             * @param include_partials: if true, all the parameter samples
             * generated during the training process will also be saved under a
             * subdirectory.
             */
            DBNSaver(const std::shared_ptr<DynamicBayesNet>& model,
                     const std::shared_ptr<DBNTrainer>& trainer,
                     const std::string& output_folder_path,
                     bool include_partials);

            ~DBNSaver();

            //------------------------------------------------------------------
            // Copy & Move constructors/assignments
            //------------------------------------------------------------------

            // Copy constructor and assignment should be deleted to avoid
            // implicit slicing and loss of polymorphic behaviour in the
            // subclasses. To deep copy, the clone method must be used.
            DBNSaver(const DBNSaver&) = delete;

            DBNSaver& operator=(const DBNSaver&) = delete;

            DBNSaver(DBNSaver&&) = default;

            DBNSaver& operator=(DBNSaver&&) = default;

            //------------------------------------------------------------------
            // Member functions
            //------------------------------------------------------------------

            /**
             * Prepares the trainer to a series of calls to the function fit by
             * performing necessary cleanups.
             */
            void prepare();

            /**
             * Saves a model's parameters into files in a specific folder.
             *
             */
            void save();

          private:
            //------------------------------------------------------------------
            // Member functions
            //------------------------------------------------------------------

            /**
             * Saves all the parameter samples generated during the training
             * process under a subdirectory of the final model directory.
             *
             * @param model_dir: directory where the final model's parameters
             * are saved.
             */
            void save_partials(const std::string& model_dir) const;

            //------------------------------------------------------------------
            // Data members
            //------------------------------------------------------------------
            std::shared_ptr<DynamicBayesNet> model;

            // Folder where the model's parameters' files will be saved.
            std::string output_folder_path;

            // Cross validation step. This is incremented at each call of the
            // function save. It can be used to identify a folder with
            // parameters for a specific cross validation step.
            int cv_step = 0;

            // An instance of the trainer is important here so we can access
            // all the parameter samples generated by it (or loaded by it) and
            // estimate probabilities over all sampled models. That way we
            // can compute density confidences over estimates.
            std::shared_ptr<DBNTrainer> trainer;

            // Indicates whether the parameter samples generated during the
            // training process must be saved or not.
            bool include_partials;
        };

    } // namespace model
} // namespace tomcat
