#!/bin/bash

set -u

# Set the ROOT environment variable, assuming that the directory structure
# mirrors that of the git repository.
ROOT="$(cd "$( dirname "${BASH_SOURCE[0]}" )/../" >/dev/null 2>&1 && pwd)"
export ROOT

###############################################################################

source ${ROOT}/tools/configuration_helpers
set_local_configuration

detect_ci
detect_os

__build_tmm() {
    pushd "${ROOT}"
        echo "Building TMM in $(pwd)"

        /bin/rm -rf build
        mkdir build

        pushd build > /dev/null
            if [[ $OSTYPE == "linux-gnu" ]]; then
                NJOBS=$(nproc)
            else
                NJOBS=$(sysctl -n hw.ncpu)
            fi

            if ! cmake ${ROOT}; then exit 1; fi

            if ! make -j $NJOBS; then exit 1; fi
        popd > /dev/null
    popd > /dev/null
}

_install_tmm() {
    if (( ${INSTALL_DEPENDENCIES:-1} )); then
        if ! ${ROOT}/tools/install_dependencies; then exit 1; fi
    else
        echo "INSTALL_DEPENDENCIES has been set to 0, so we skip the automatic"\
             "installation of TMM dependencies, and assume that you have"\
             "already installed the prerequisites (either manually or using a"\
             "previous invocation of the install script.)"
    fi
    __build_tmm

    echo " "
    echo "Finished installing TMM in ${ROOT}!"
    echo " "
}

_install_tmm
exit 0
