#!/usr/bin/env bash

set -euo pipefail

# Script to split ASIST data in two directories: one for training and the other
# for evaluation.  Symbolic links are created to avoid moving files from the
# main directory. This script assumes asist data was synchronized already.
#
# It also assumes that there's a file called eval_list.txt in the
# study-1_2020.08 directory, containing the list of filenames to evaluate. All
# of the other files not in this list will be used for training the model.

# Set the ROOTDIR environment variable, assuming that the directory structure
# mirrors that of the git repository.
ROOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../" >/dev/null 2>&1 && pwd)"
export ROOTDIR

GCS_DIR=study-1_2020.08
ORIGINAL_DATA_DIR="$ROOTDIR"/data/asist/$GCS_DIR
SPLIT_DATA_DIR="$ORIGINAL_DATA_DIR"_split
TRAINING_DIR="$SPLIT_DATA_DIR"/train
EVAL_DIR="$SPLIT_DATA_DIR"/eval
TRAIN_LIST="$SPLIT_DATA_DIR"/train_list.txt
EVAL_LIST="$SPLIT_DATA_DIR"/eval_list.txt

# Always clear the directories to avoid links to old files
rm -rf $TRAINING_DIR $EVAL_DIR
mkdir -p $TRAINING_DIR $EVAL_DIR

if [ ! -f $EVAL_LIST ]; then
   echo "File $EVAL_LIST does not exist."
   exit 1
fi

# Create symbolic links in the training directory for the files listed in
# train_list.txt
while IFS= read -r trial; do
  for file in $(ls "$ORIGINAL_DATA_DIR" | egrep -i "trial-$trial");
  do
    ln -s "$ORIGINAL_DATA_DIR/$file" $TRAINING_DIR
  done
done < $TRAIN_LIST

# Create symbolic links in the evaluation directory for the files listed in
# eval_list.txt. We only get the latest version published (version 3).
while IFS= read -r trial; do
  for file in $(ls "$ORIGINAL_DATA_DIR" | egrep -i "trial-$trial" | egrep -i "Vers-3");
  do
    ln -s "$ORIGINAL_DATA_DIR/$file" $EVAL_DIR
  done
done < $EVAL_LIST

# If no file exists for the filenames listed in eval_list.txt, the exit code
# will be 1. However, the error was already handled by not creating symbolic
# links in the evaluation directory. Therefore, we force an sucessful exit
# code if the execution reached the end of the script without any other issues.
exit 0

