# This is a basic workflow to help you get started with Actions

name: Continuous Integration

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    if: github.repository == 'ml4ai/tomcat-tmm'
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]


    steps:
    - uses: actions/checkout@v2

    - name: Continuous Integration
      run: |
        ./tools/install
